### ISSUE TITLE
ImportError: cannot import name 'Language'

### ISSUE THREAD

**Issue by markusdr** [BramVanroy/spacy_download#1]
Hello, I'm getting an error when trying to import spacy_download:

```
$ python
Python 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from spacy_download import load_spacy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/e/lib/python3.6/site-packages/spacy_download/__init__.py", line 3, in <module>
    from .load import load_spacy
  File "/anaconda3/envs/e/lib/python3.6/site-packages/spacy_download/load.py", line 3, in <module>
    from spacy import Language
ImportError: cannot import name 'Language'
```
I have an admittedly old spacy:
```
$ pip list | grep spacy
spacy                              2.3.4
spacy-download                     1.0.0
```

**Comment by BramVanroy** [comment]
As you mention, this utility is only intended for spaCy>=3;<4 so unfortunately I cannot help with that. If you have a hugely important use-case for this, I might have a look whether I can make a spaCy 2 branch.
